sudo: false

language: node_js
node_js:
  - "node"
  - "9"
  - "8"
  - "6"
  - "4"

os:
  - osx
  - linux

osx_image: xcode9.2

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=gcc-7 && CXX=g++-7; fi
  - npm run fetch-libsodium

before_deploy:
  - ARCHIVE_NAME="${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME-`uname -m`.tar"
  - npm run prebuild
  - tar --create --verbose --file="$ARCHIVE_NAME" --directory "$TRAVIS_BUILD_DIR/prebuilds" .

deploy:
  provider: releases
  draft: false
  prerelease: true
  api_key:
  file: "$ARCHIVE_NAME"
  skip_cleanup: true
  on:
    tags: true
    node: "8"
