sudo: false
language: node_js
node_js:
- node
- lts/*
- '8'
- '6'
- '4'
os:
- osx
- linux
- windows
osx_image: xcode9.2
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=gcc-7 && CXX=g++-7; fi
- npm run fetch-libsodium
before_deploy:
- ARCHIVE_NAME="${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME-`uname -m`.tar"
- npm run prebuild
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm run prebuild-ia32; ARCHIVE_NAME="${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME-all.tar";  fi
- tar --create --verbose --file="$ARCHIVE_NAME" --directory "$TRAVIS_BUILD_DIR/prebuilds" .
deploy:
  provider: releases
  draft: false
  prerelease: true
  api_key:
    secure: S5vD/ctnWEc5RVDTbvviYFSF/vRXFtKjpC5ukEt6FgzbSfq0677DtMszvW0i8drcgyuVOhochMfar0O9yPiXIVJYQvLh+C86Ox9JYhPoOS1bRQ4tDguQU4vmkCxo/qN1yxdcjvP6ZHEFOVuzy7jLljL6DlEc5dLDVkATzfiazcOWkLfqT9bi/S8F/wcU248v6TSNqxKO0yVsBk9q9LVx9wAvBogM+5NYzL78ViflisN/QUl9VF11QCLxhfnrkEIQ1LVhGt8WbFn2q8Jf0QMxTSCY1Bb3HbIc7GDbJSO2WI4Bdrw60MiovAfQH7rGvtXhO6emDK1dGDCHa5xpdyE8md1sQOU62izY3UAqeOCFitAM5HiYSrtKzn6yGu1POyusW4xfT5cq9OP81xj0z0uzsoj0PfCmhNvH9JEetvr8rQSq53N9RRzWbr2ua0onqf0GcqETVq1a01gFDq5FEBEslr33PjC8Ow4ySHYOgfvWDacmH1vpgk4/+vk5/p2sbQkJWzNEhoodtFFLNvNYDwYm4yr6MfIh9AXSIZtK9lIr/kaM6NlD8Rf13OYvQhOCN6P5CLDsJgAR84303OuPAs8aDeAgP/iJt5qdAItAmBW1A4CgY5grgrXLKzcjbolaFPgOEPCzHYm0TzOSZoTjNIB0kOSJWsyCZ09AgW7DHg0LxMM=
  file: $ARCHIVE_NAME
  skip_cleanup: true
  on:
    tags: true
    node: 'node'
