build: false

skip_branch_with_pr: true

environment:
  matrix:
    - nodejs_version: "Current"
    - nodejs_version: "LTS"
    - nodejs_version: "8"
    - nodejs_version: "6"
    - nodejs_version: "4"

configuration: Release
platform:
  - x86
  - x64

install:
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm run fetch-libsodium
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

before_package:
  - npm run prebuild

artifacts:
  - path: prebuilds
    name: $(APPVEYOR_REPO_TAG_NAME)-win-$(PLATFORM)
    type: zip

deploy:
  - provider: GitHub
    artifact: /.*\.zip/
    draft: false
    prerelease: true
    auth_token:
      secure: eW9UF3UNoIwdfhouoXsJkGy9++UEdNct2ARHCJ6xHDQ3B11j1PpObCd6kupuYUK2
    on:
      appveyor_repo_tag: true
      nodejs_version: "Current"
